### ISSUE TITLE
add link of https://reliability.re/

### ISSUE THREAD

**Issue by tormath1** [sre-paris/reliability.re#66]
It's just an idea I got while reading tweets from the Twitter account: when we share a "long" post on Twitter, the tweet will be split (in order to not truncate the content). What do you think about keeping the post "short" and add a link add the end to the https://reliability.re/ website (we could even extend it to to all posts) ? 

To have something like: 

> blablabla
> blablabla
> more at https://reliability.re/

**Comment by pabluk** [comment]
I'll take a look at this later, but here are my first thoughts on this: 

1. Regarding Twitter's link previews, the order is important, the last link on the tweet will generate the preview. In this case, the "more at reliability.re" link will need to be placed before the target link.
2. Every additional link on a tweet could consume 23 characters, reducing the available space for content.
3. At the beginning the idea was to keep all the content on the same social platform were the content is posted, so adding an additional hop to get the full content could increase user's friction.
4. There's no "official" page dedicated to individual posts on the website, all the posts are published directly on the homepage https://reliability.re/ but looking at the [RSS source page](https://reliability.re/links/index.xml) we can find the `guid` field that's a link to a  not very well-formatted page. For example [this one](https://reliability.re/links/2020-12-22-interrupt-reduction-projects/).

I think that 3. and 4. could be reviewed and reworked if needed, because they were very early decisions.

**Comment by tormath1** [comment]
Ok, thanks for your quick answer.

With the way we are currently sharing, we can click on the URL of the source OR the github/twitter username. The idea behinds this issue is to give a way for the reader to find out the "original" post on http://reliability.re/ but IDK "how" that's why I submitted the idea of "more at ..." .

One other way to share, would be to share the link like the one you shared (https://reliability.re/links/2020-12-22-interrupt-reduction-projects/) on media (twitter/telegram/etc.)

You'll get the following pattern:

```
tweet -> click on https://reliability.re/links/2020-12-22-interrupt-reduction-projects/ link -> you're on the website  -> click on the original URL of the shared content if interested
```

**Comment by tormath1** [comment]
I guess we can close this issue then. Thanks for your answers :D

**Comment by pabluk** [comment]
Sorry for the late reply @tormath1, but yeah maybe it's better close this issue now review it in the future is needed.
